# -*- coding: utf-8 -*-
"""Copy of Beginner Workshop Completed.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cyGCtZ1Q-YqepEqaaSEz3_iru8nQexof

#VandyHacks Beginner Workshop: Web Scraping!

---

##Base code:
"""

import requests 
from bs4 import BeautifulSoup as bs 
import pandas as pd
import json

page = requests.get("https://www.billboard.com/charts/hot-100") #get the page
soup = bs(page.content) #get the page source code

file = [[],[],[]]
titles = soup.find_all('span', attrs={"class":"chart-element__information__song"})
artists = soup.find_all('span', attrs={"class":"chart-element__information__artist"})
for title in titles:
  file[0].append(title.text)

for artist in artists:
  file[1].append(artist.text)

front = "https://www.google.com/search?q="
end = "&tbm=isch&sxsrf=ALeKk009XLBpO9WArJSBK0diCwqdxcwrBQ%3A1624834086280&source=hp&biw=1536&bih=722&ei=JgDZYJrODo7r-wTJp42YCg&oq=jake+enhypen&gs_lcp=CgNpbWcQAzIFCAAQsQMyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAMgIIADICCAA6BAgjECc6CAgAELEDEIMBOgYIABAKEBhQ3ANY8hdggRloAXAAeACAAYcBiAHUCZIBBDExLjKYAQCgAQGqAQtnd3Mtd2l6LWltZw&sclient=img&ved=0ahUKEwia-Z3U8rjxAhWO9Z4KHclTA6MQ4dUDCAc&uact=5"
import random

for i in range(100):
  img_page = requests.get(front+str(file[0][i])+str(file[1][i])+end)
  img_page = bs(img_page.content)
  data = img_page.find_all('img', attrs={"class":"yWs4tf"})
  r = random.randint(1, len(data)-1)
  file[2].append(data[r]['src'])

import pandas as pd
import json
j = pd.DataFrame(file, index=['name', 'artist', 'image']).to_json('billbo.json')